src/accounts/urls.py
# -*- encoding: utf-8 -*-

from django.urls import path

from .views import CustomLoginView, CustomLogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
]

src/reslab_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("sample_tracker.urls")),
]

src/sample_tracker/urls.py
from django.urls import path

from . import views

app_name = "sample_tracker"
urlpatterns = [
    path(
        "", views.DashboardView.as_view(), name="dashboard_home"
    ),  # Default route for the dashboard
    # =====================
    # Address URLs
    # =====================
    path("addresses/", views.AddressListView.as_view(), name="address_list"),
    path("addresses/add/", views.AddressCreateView.as_view(), name="address_create"),
    path(
        "addresses/<int:pk>/edit/",
        views.AddressUpdateView.as_view(),
        name="address_update",
    ),
    path(
        "addresses/<int:pk>/delete/",
        views.AddressDeleteView.as_view(),
        name="address_delete",
    ),
    # =====================
    # Study URLs
    # =====================
    path("studies/", views.StudyListView.as_view(), name="study_list"),
    path("studies/<int:pk>/", views.StudyDetailView.as_view(), name="study_detail"),
    path("studies/add/", views.StudyCreateView.as_view(), name="study_create"),
    path(
        "studies/<int:pk>/edit/", views.StudyUpdateView.as_view(), name="study_update"
    ),
    path(
        "studies/<int:pk>/delete/", views.StudyDeleteView.as_view(), name="study_delete"
    ),
    # =====================
    # Study Site URLs
    # =====================
    path("study-sites/", views.StudySiteListView.as_view(), name="study_site_list"),
    path(
        "study-sites/<int:pk>/",
        views.StudySiteDetailView.as_view(),
        name="study_site_detail",
    ),
    path(
        "study-sites/add/",
        views.StudySiteCreateView.as_view(),
        name="study_site_create",
    ),
    path(
        "study-sites/<int:pk>/edit/",
        views.StudySiteUpdateView.as_view(),
        name="study_site_update",
    ),
    path(
        "study-sites/<int:pk>/delete/",
        views.StudySiteDeleteView.as_view(),
        name="study_site_delete",
    ),
    # =====================
    # Sample URLs
    # =====================
    path("samples/", views.SampleListView.as_view(), name="sample_list"),
    path("samples/<int:pk>/", views.SampleDetailView.as_view(), name="sample_detail"),
    path("samples/add/", views.SampleCreateView.as_view(), name="sample_create"),
    path(
        "samples/<int:pk>/edit/", views.SampleUpdateView.as_view(), name="sample_update"
    ),
    path(
        "samples/<int:pk>/delete/",
        views.SampleDeleteView.as_view(),
        name="sample_delete",
    ),
    # =====================
    # Plate URLs
    # =====================
    path("plates/", views.PlateListView.as_view(), name="plate_list"),
    path("plates/add/", views.PlateCreateView.as_view(), name="plate_create"),
    path("plates/<int:pk>/edit/", views.PlateUpdateView.as_view(), name="plate_update"),
    path(
        "plates/<int:pk>/delete/", views.PlateDeleteView.as_view(), name="plate_delete"
    ),
    # =====================
    # DNA Extraction URLs
    # =====================
    path(
        "dna-extractions/",
        views.DNAExtractionListView.as_view(),
        name="dna_extraction_list",
    ),
    path(
        "dna-extractions/add/",
        views.DNAExtractionCreateView.as_view(),
        name="dna_extraction_create",
    ),
    path(
        "dna-extractions/<int:pk>/edit/",
        views.DNAExtractionUpdateView.as_view(),
        name="dna_extraction_update",
    ),
    path(
        "dna-extractions/<int:pk>/delete/",
        views.DNAExtractionDeleteView.as_view(),
        name="dna_extraction_delete",
    ),
    # =====================
    # Molecular Diagnostic URLs
    # =====================
    path(
        "molecular-diagnostics/",
        views.MolecularDiagnosticListView.as_view(),
        name="molecular_diagnostic_list",
    ),
    path(
        "molecular-diagnostics/add/",
        views.MolecularDiagnosticCreateView.as_view(),
        name="molecular_diagnostic_create",
    ),
    path(
        "molecular-diagnostics/<int:pk>/edit/",
        views.MolecularDiagnosticUpdateView.as_view(),
        name="molecular_diagnostic_update",
    ),
    path(
        "molecular-diagnostics/<int:pk>/delete/",
        views.MolecularDiagnosticDeleteView.as_view(),
        name="molecular_diagnostic_delete",
    ),
    # =====================
    # Storage URLs
    # =====================
    path("storages/", views.StorageListView.as_view(), name="storage_list"),
    path("storages/add/", views.StorageCreateView.as_view(), name="storage_create"),
    path(
        "storages/<int:pk>/edit/",
        views.StorageUpdateView.as_view(),
        name="storage_update",
    ),
    path(
        "storages/<int:pk>/delete/",
        views.StorageDeleteView.as_view(),
        name="storage_delete",
    ),
    # =====================
    # Quality Check URLs
    # =====================
    path(
        "quality-checks/",
        views.QualityCheckListView.as_view(),
        name="quality_check_list",
    ),
    path(
        "quality-checks/add/",
        views.QualityCheckCreateView.as_view(),
        name="quality_check_create",
    ),
    path(
        "quality-checks/<int:pk>/edit/",
        views.QualityCheckUpdateView.as_view(),
        name="quality_check_update",
    ),
    path(
        "quality-checks/<int:pk>/delete/",
        views.QualityCheckDeleteView.as_view(),
        name="quality_check_delete",
    ),
    # =====================
    # Pooling URLs
    # =====================
    path("poolings/", views.PoolingListView.as_view(), name="pooling_list"),
    path("poolings/add/", views.PoolingCreateView.as_view(), name="pooling_create"),
    path(
        "poolings/<int:pk>/edit/",
        views.PoolingUpdateView.as_view(),
        name="pooling_update",
    ),
    path(
        "poolings/<int:pk>/delete/",
        views.PoolingDeleteView.as_view(),
        name="pooling_delete",
    ),
]

src/sample_tracker/views.py
from django.db.models import Count, Q
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .forms import (
    AddressForm,
    DNAExtractionForm,
    MolecularDiagnosticForm,
    PlateForm,
    PoolingForm,
    QualityCheckForm,
    SampleForm,
    StorageForm,
    StudyForm,
    StudySiteForm,
)
from .models import (
    Address,
    DNAExtraction,
    MolecularDiagnostic,
    Plate,
    Pooling,
    QualityCheck,
    Sample,
    Storage,
    Study,
    StudySite,
)


class DashboardView(TemplateView):
    template_name = "dashboard/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add dynamic data for the dashboard
        context["study_count"] = Study.objects.count()
        context["sample_count"] = Sample.objects.count()
        context["positive_sample_count"] = Sample.objects.filter(status="POS").count()
        context["negative_sample_count"] = Sample.objects.filter(status="NEG").count()

        # Quality Check Data
        context["accepted_quality_count"] = QualityCheck.objects.filter(
            status="Accepted"
        ).count()
        context["rejected_quality_count"] = QualityCheck.objects.filter(
            status="Rejected"
        ).count()

        # Recent Samples (Limit to 5 for display)
        context["recent_samples"] = Sample.objects.order_by("-collection_date")[:5]

        return context


# =====================
# Address Views
# =====================
class AddressListView(ListView):
    model = Address
    template_name = "address_list.html"
    context_object_name = "addresses"


class AddressCreateView(CreateView):
    model = Address
    form_class = AddressForm
    template_name = "address_form.html"
    success_url = reverse_lazy("address_list")


class AddressUpdateView(UpdateView):
    model = Address
    form_class = AddressForm
    template_name = "address_form.html"
    success_url = reverse_lazy("address_list")


class AddressDeleteView(DeleteView):
    model = Address
    template_name = "confirm_delete.html"
    success_url = reverse_lazy("address_list")


# =====================
# Study Views
# =====================
class StudyListView(ListView):
    model = Study
    template_name = "sample_tracker/study/study_list.html"
    context_object_name = "studies"


class StudyDetailView(DetailView):
    model = Study
    template_name = "sample_tracker/study/study_detail.html"
    context_object_name = "study"


class StudyCreateView(CreateView):
    model = Study
    form_class = StudyForm
    template_name = "sample_tracker/study/study_form.html"
    success_url = reverse_lazy("sample_tracker:study_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class StudyUpdateView(UpdateView):
    model = Study
    form_class = StudyForm
    template_name = "sample_tracker/study/study_form.html"
    success_url = reverse_lazy("sample_tracker:study_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class StudyDeleteView(DeleteView):
    model = Study
    template_name = "sample_tracker/study/confirm_delete.html"
    success_url = reverse_lazy("sample_tracker:study_list")


# =====================
# Study Site Views
# =====================
class StudySiteListView(ListView):
    model = StudySite
    template_name = "sample_tracker/study-site/study_site_list.html"
    context_object_name = "study_sites"


class StudySiteDetailView(DetailView):
    model = StudySite
    template_name = "sample_tracker/study-site/study_site_detail.html"
    context_object_name = "study_site"


class StudySiteCreateView(CreateView):
    model = StudySite
    form_class = StudySiteForm
    template_name = "sample_tracker/study-site/study_site_form.html"
    success_url = reverse_lazy("sample_tracker:study_site_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class StudySiteUpdateView(UpdateView):
    model = StudySite
    form_class = StudySiteForm
    template_name = "sample_tracker/study-site/study_site_form.html"
    success_url = reverse_lazy("sample_tracker:study_site_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class StudySiteDeleteView(DeleteView):
    model = StudySite
    template_name = "confirm_delete.html"
    success_url = reverse_lazy("sample_tracker:study_site_list")


# =====================
# Sample Views
# =====================
class SampleListView(ListView):
    model = Sample
    template_name = "sample_tracker/sample/sample_list.html"
    context_object_name = "samples"


class SampleDetailView(DetailView):
    model = Sample
    template_name = "ssample_tracker/ample/sample_detail.html"
    context_object_name = "sample"


class SampleCreateView(CreateView):
    model = Sample
    form_class = SampleForm
    template_name = "sample_tracker/sample/sample_form.html"
    success_url = reverse_lazy("sample_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class SampleUpdateView(UpdateView):
    model = Sample
    form_class = SampleForm
    template_name = "ssample_tracker/ample/sample_form.html"
    success_url = reverse_lazy("sample_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class SampleDeleteView(DeleteView):
    model = Sample
    template_name = "sample_tracker/sample/confirm_delete.html"
    success_url = reverse_lazy("sample_list")


# =====================
# Plate Views
# =====================
class PlateListView(ListView):
    model = Plate
    template_name = "plate/plate_list.html"
    context_object_name = "plates"


class PlateCreateView(CreateView):
    model = Plate
    form_class = PlateForm
    template_name = "plate/plate_form.html"
    success_url = reverse_lazy("plate_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class PlateUpdateView(UpdateView):
    model = Plate
    form_class = PlateForm
    template_name = "plate/plate_form.html"
    success_url = reverse_lazy("plate_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class PlateDeleteView(DeleteView):
    model = Plate
    template_name = "plate/confirm_delete.html"
    success_url = reverse_lazy("plate_list")


# =====================
# DNA Extraction Views
# =====================
class DNAExtractionListView(ListView):
    model = DNAExtraction
    template_name = "dna-extraction/dna_extraction_list.html"
    context_object_name = "dna_extractions"


class DNAExtractionDetailView(DetailView):
    model = DNAExtraction
    template_name = "dna-extraction/dna_extraction_detail.html"
    context_object_name = "dna_extraction"


class DNAExtractionCreateView(CreateView):
    model = DNAExtraction
    form_class = DNAExtractionForm
    template_name = "dna-extraction/dna_extraction_form.html"
    success_url = reverse_lazy("dna_extraction_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class DNAExtractionUpdateView(UpdateView):
    model = DNAExtraction
    form_class = DNAExtractionForm
    template_name = "dna-extraction/dna_extraction_form.html"
    success_url = reverse_lazy("dna_extraction_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class DNAExtractionDeleteView(DeleteView):
    model = DNAExtraction
    template_name = "dna-extraction/confirm_delete.html"
    success_url = reverse_lazy("dna_extraction_list")


# =====================
# Molecular Diagnostics Views
# =====================
class MolecularDiagnosticListView(ListView):
    model = MolecularDiagnostic
    template_name = "molecular-diagnostic/molecular_diagnostic_list.html"
    context_object_name = "molecular_diagnostics"


class MolecularDiagnosticDetailView(DetailView):
    model = MolecularDiagnostic
    template_name = "molecular-diagnostic/molecular_diagnostic_detail.html"
    context_object_name = "molecular_diagnostic"


class MolecularDiagnosticCreateView(CreateView):
    model = MolecularDiagnostic
    form_class = MolecularDiagnosticForm
    template_name = "molecular-diagnostic/molecular_diagnostic_form.html"
    success_url = reverse_lazy("molecular_diagnostic_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False
        return context


class MolecularDiagnosticUpdateView(UpdateView):
    model = MolecularDiagnostic
    form_class = MolecularDiagnosticForm
    template_name = "molecular-diagnostic/molecular_diagnostic_form.html"
    success_url = reverse_lazy("molecular_diagnostic_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class MolecularDiagnosticDeleteView(DeleteView):
    model = MolecularDiagnostic
    template_name = "molecular-diagnostic/confirm_delete.html"
    success_url = reverse_lazy("molecular_diagnostic_list")


# =====================
# Storage Views
# =====================

src/templates/sample_tracker/study/study_detail.html
{% extends "base.html" %}
{% block title %}Study Detail{% endblock %}

{% block content %}
<div class="ui grid stackable padded">
    <div class="twelve wide column">
        <h2 class="ui header">Study Detail</h2>
        <table class="ui celled table">
            <tbody>
                <tr>
                    <td>ID</td>
                    <td>{{ study.id }}</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>{{ study.name }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ study.description }}</td>
                </tr>
                <tr>
                    <td>Start Date</td>
                    <td>{{ study.start_date }}</td>
                </tr>
                <tr>
                    <td>End Date</td>
                    <td>{{ study.end_date }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="four wide column">
        <a href="{% url 'sample_tracker:study_update' study.id %}" class="ui button">Edit Study</a>
        <a href="{% url 'sample_tracker:study_delete' study.id %}" class="ui button">Delete Study</a>
    </div>
</div>
{% endblock %}

src/templates/sample_tracker/study/study_form.html
{% extends "base.html" %}
{% block title %}Study Form{% endblock %}

{% block content %}
<div class="ui grid stackable padded">
    <div class="twelve wide column">
        <h2 class="ui header">{% if is_update %}Update Study{% else %}Add Study{% endif %}</h2>
        <div class="ui raised segment">
            <form class="ui form" method="post" action="{% if is_update %}{% url 'sample_tracker:study_update' study.id %}{% else %}{% url 'sample_tracker:study_create' %}{% endif %}">
                {% csrf_token %}
                <div class="field">
                    <label>Name</label>
                    {{ form.name }}
                    <!-- Field errors -->
                    {% if form.name.errors %}
                    <div class="ui error message">
                        <ul class="ui list">
                            {% for error in form.name.errors %}
                            <li class="item">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>Description</label>
                    {{ form.description }}
                    <!-- Field errors -->
                    {% if form.description.errors %}
                    <div class="ui error message">
                        <ul class="ui list">
                            {% for error in form.site.errors %}
                            <li class="item">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
                <div class="equal width fields">
                    <div class="field">
                        <label>Start Date</label>
                        {{ form.start_date }}
                        <!-- Field errors -->
                        {% if form.start_date.errors %}
                        <div class="ui error message">
                            <ul class="ui list">
                                {% for error in form.start_date.errors %}
                                <li class="item">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                    <div class="field">
                        <label>End Date</label>
                        {{ form.end_date }}
                        <!-- Field errors -->
                        {% if form.end_date.errors %}
                        <div class="ui error message">
                            <ul class="ui list">
                                {% for error in form.end_date.errors %}
                                <li class="item">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <button class="ui button" type="submit">{% if is_update %}Update{% else %}Add{% endif %}</button>
            </form>
        </div>
    </div>
    <div class="four wide column">
        <a href="{% url 'sample_tracker:study_list' %}" class="ui button">Back to Study List</a>
    </div>
</div>
{% endblock %}

src/templates/sample_tracker/study/study_list.html
{% extends "base.html" %}
{% block title %}Study List{% endblock %}

{% block content %}
<div class="ui grid stackable padded">
    <div class="twelve wide column">
        <h2 class="ui header">Study List</h2>
        <div class="ui divider"></div>

        <!-- Study List -->
        <div class="ui raised segment">
            <h3 class="ui header">Studies</h3>
            <table class="ui celled table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Period</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for study in studies %}
                    <tr>
                        <td>{{ study.name }}</td>
                        <td>{{ study.start_date }} - {{ study.end_date }}</td>
                        <td>
                            <a href="{% url 'sample_tracker:study_detail' study.id %}" class="ui button">View</a>
                            <a href="{% url 'sample_tracker:study_update' study.id %}" class="ui button">Edit</a>
                            <a href="{% url 'sample_tracker:study_delete' study.id %}" class="ui button">Delete</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No studies available.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="four wide column">
        <a href="{% url 'sample_tracker:study_create' %}" class="ui button">Create Study</a>
    </div>
</div>
 {% endblock %}